// Generated by CoffeeScript 1.10.0
(function() {
  var UI, card, isStarted, timer;

  UI = require('ui');

  card = new UI.Card({
    title: 'Reading'
  });

  timer = new Date();

  isStarted = false;

  card.on('click', function() {
    var elapsed;
    if (isStarted) {
      isStarted = false;
      elapsed = new Date() - timer;
      return card.body('session time: ' + Math.floor(elapsed / 1000) + ' seconds');
    } else {
      isStarted = true;
      return card.body('started');
    }
  });

  card.show();

}).call(this);
