// Generated by CoffeeScript 1.10.0
(function() {
  var Timer, UI, card, timer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Timer = (function() {
    function Timer() {
      this.elapsed = bind(this.elapsed, this);
      this.stop = bind(this.stop, this);
      this.start = bind(this.start, this);
      this.isStarted = bind(this.isStarted, this);
      this.started = false;
    }

    Timer.prototype.isStarted = function() {
      return this.started;
    };

    Timer.prototype.start = function() {
      this.startedAt = new Date();
      return this.started = true;
    };

    Timer.prototype.stop = function() {
      this.started = false;
      return this.stoppedAt = new Date();
    };

    Timer.prototype.elapsed = function() {
      var elapsed;
      elapsed = this.stoppedAt - this.startedAt;
      return Math.floor(elapsed / 1000);
    };

    return Timer;

  })();

  UI = require('ui');

  timer = new Timer();

  card = new UI.Card({
    title: 'Reading'
  });

  card.on('click', function() {
    if (timer.isStarted()) {
      timer.stop();
      return card.body("session time: " + (timer.elapsed()) + " sec");
    } else {
      timer.start();
      return card.body('started');
    }
  });

  card.show();

}).call(this);
