// Generated by CoffeeScript 1.10.0
(function() {
  var Timer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Timer = (function() {
    function Timer() {
      this.elapsed = bind(this.elapsed, this);
      this.stop = bind(this.stop, this);
      this.started = bind(this.started, this);
      this.start = bind(this.start, this);
      this.started = false;
    }

    Timer.prototype.start = function() {
      this.started = true;
      return console.log("status: " + this.status);
    };

    Timer.prototype.started = function() {
      this.startedAt = new Date();
      return this.started = true;
    };

    Timer.prototype.stop = function() {
      this.started = false;
      return this.stoppedAt = new Date();
    };

    Timer.prototype.elapsed = function() {
      var elapsed;
      elapsed = this.stoppedAt - this.stoppedAt;
      return Math.floor(elapsed / 1000);
    };

    return Timer;

  })();

}).call(this);
